version: "3.7"

services:
  simple-ecommerce:
    container_name: simple_ecommerce
    build:
      context: .
      dockerfile: DockerfileLocal.dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DEBUG: "1"
      hostname: "localhost"
      webappport: "8000"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: simple_ecommerce
      POSTGRES_HOST: ecommerce_postgres
      POSTGRES_PORT: 5432
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ecommerce-network

  postgres:
    image: postgres
    container_name: ecommerce_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: simple_ecommerce
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres && psql -U postgres -d simple_ecommerce -c 'SELECT 1;'"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ecommerce-network

volumes:
  pgdata:

networks:
  ecommerce-network:
    driver: bridge
