# Generated by Django 5.2.3 on 2025-06-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fxrate",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
