# Generated by Django 5.2.3 on 2025-06-28 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0002_alter_fxrate_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="currency",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ecommerce.currency",
            ),
        ),
    ]
