# Generated by Django 5.1.6 on 2025-06-14 11:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_journalentry_account_journalentryline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productprice',
            options={'ordering': ['-begin_date']},
        ),
        migrations.AddField(
            model_name='inventory',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productprice',
            name='begin_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='productprice',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='ecommerce.product'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='ecommerce.product'),
        ),
        migrations.AddConstraint(
            model_name='productprice',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__isnull', True)), fields=('product',), name='only_one_active_price_per_product'),
        ),
    ]
