# Generated by Django 5.2.3 on 2025-07-21 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0005_order_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment",
                to="ecommerce.order",
            ),
        ),
    ]
