# Generated by Django 5.2.3 on 2025-09-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
