# Generated by Django 5.2.3 on 2025-09-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0009_alter_journalentry_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalentryline",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
