# Generated by Django 5.2.3 on 2025-09-20 12:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0012_alter_fxrate_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="fxrate",
            name="unique_currency_pair_startdate",
        ),
    ]
