# Generated by Django 5.2.3 on 2025-09-22 12:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0015_weightcost"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfitRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("modified_at", models.DateTimeField(auto_now=True, null=True)),
                ("profit_rate", models.FloatField()),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                ("end_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="weightcost",
            name="only_one_active_weight_cost",
        ),
        migrations.AddConstraint(
            model_name="weightcost",
            constraint=models.UniqueConstraint(
                condition=models.Q(("end_date__isnull", True)),
                fields=("cost_per_kg", "currency"),
                name="only_one_active_weight_cost_global",
            ),
        ),
        migrations.AddField(
            model_name="profitrate",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modified_%(class)ss",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="profitrate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("end_date__isnull", True)),
                fields=("profit_rate",),
                name="only_one_active_profit_rate",
            ),
        ),
    ]
