# Generated by Django 5.2.3 on 2025-09-22 12:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ecommerce",
            "0017_remove_weightcost_only_one_active_weight_cost_global_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="weightcost",
            name="only_one_active_weight_cost_global",
        ),
        migrations.AddConstraint(
            model_name="weightcost",
            constraint=models.UniqueConstraint(
                condition=models.Q(("end_date__isnull", True)),
                fields=("cost_per_kg",),
                name="only_one_active_weight_cost_global",
            ),
        ),
    ]
