# Generated by Django 5.2.3 on 2025-10-04 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0019_incomename_income_spendingname_spending'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('weight', models.FloatField(help_text='Weight in kilograms')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(help_text='The product this weight record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='ecommerce.product')),
            ],
            options={
                'verbose_name': 'Product Weight',
                'verbose_name_plural': 'Product Weights',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('product',), name='unique_product_weight')],
            },
        ),
    ]
